if $tracelevel then {
	strace $tracelevel
}

set prms_id 0
set bug_id 0

set testfile mips_pro
set srcfile ${srcdir}/$subdir/${testfile}.c
set binfile ${objdir}/${subdir}/${testfile}
if  { [compile "${srcfile} -g -o ${binfile}"] != "" } {
    perror "Couldn't compile ${srcfile}"
    return -1
}

gdb_reinitialize_dir $srcdir/$subdir
gdb_load $binfile

if [runto middle] then {
    # PR 3016
    gdb_test "backtrace" "#0.*middle.*#1.*top.*#2.*main.*"
}
return 0
